### ISSUE TITLE
Redesigning modular menus.

### ISSUE THREAD

**Issue by MeanEYE** [ArseniyK/archiver#1]
Hello @ArseniyK, long time no chat. Am currently upgrading the way popup menu looks and works. This is its new form:

![image](https://user-images.githubusercontent.com/1911594/151718774-8dec26bc-f10a-468b-924d-018e279954f9.png)

Idea behind it is to allow more complex interfaces to be built while keeping everything simple and slimmed down. Issue is however is that I will have to break compatibility with this plugin. While custom entries in "open with" menu are simple to deal with by providing mime type and commands to execute selection with, expanding path operations is not all that simple am afraid.

This plugin I assume would extend "Path operations" sub-menu above.

![image](https://user-images.githubusercontent.com/1911594/151718842-b73855ac-9e32-4b43-9126-6cce8ac587db.png)

Extending this menu would be possible in couple of ways. Either adding "Extract here" options in the menu itself, or creating another sub-menu where all of the operations would sit. In either of these cases current approach using `Gtk.MenuItem` will not work and will have to switch to `Gtk.ModelButton`.

Now my question is if this plugin is still maintained and should I create PR. If so, which form would you like this upgrade to take?

**Comment by ArseniyK** [comment]
Hello @MeanEYE.

I have not used Sunflower or any file manager for a long time. So it can be considered that this and my other plugins are abandoned.
If you think this plugin is useful for sunflower users, it might be better to merge it into the main sunflower repository

**Comment by MeanEYE** [comment]
Very well. I plan on completing archive support and thus deprecating this plugin. Other ones I might merge back or at least fork. Thank you for all your contributions. All the best!
